version: 2
updates:
- package-ecosystem: gradle
  directory: "/g11n-ws"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: master
  ignore:
  - dependency-name: org.springframework.boot:spring-boot-gradle-plugin
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: g11n-java-client
