dist: trusty
language: node_js
addons:
  sonarcloud:
    organization: $SONAR_ORG
    token:
      secure: $SONAR_TOKEN
node_js:
  - "7"
python:
  - "3.4"
jobs:
  include:
    - stage: unit test
      script:
        - npm install --registry https://registry.npmjs.org
        - npm run test
    - stage: auto test
      script:
        - mkdir -p g11n-js-client
        - shopt -s extglob
        - mv !(g11n-js-client) g11n-js-client/
        - mv .npmignore g11n-js-client/
        - git clone --branch=master https://github.com/singleton-demo/singleton-1.git service
        - git clone --branch=devops https://github.com/singleton-demo/singleton-1.git devops
        - mkdir -p service/g11n-ws/vip-manager-i18n/src/main/resources/l10n/bundles/
        - cp -a devops/test/bundles/JSCoreSDKTest service/g11n-ws/vip-manager-i18n/src/main/resources/l10n/bundles/
        - cd $TRAVIS_BUILD_DIR/service/g11n-ws && ./gradlew build
        - cp $TRAVIS_BUILD_DIR/devops/deploy/i18n-service/Dockerfile $TRAVIS_BUILD_DIR/service/publish/
        - cd $TRAVIS_BUILD_DIR/service/publish && mv vip-manager-i18n-*.jar i18n-service.jar
        - docker build -t singleton .
        - docker run -d -p 8090:8090 --name singleton singleton
        - docker ps
        - cd $TRAVIS_BUILD_DIR
        - cd g11n-js-client
        - npm install --registry https://registry.npmjs.org
        - npm link
        - cd $TRAVIS_BUILD_DIR/devops/test/client/jscoresdk
        - npm link @singleton/singleton-core-sdk
        - npm install --registry https://registry.npmjs.org
        - ./node_modules/.bin/jest
