language: java
addons:
  sonarcloud:
    organization: $SONAR_ORG
    token:
      secure: $SONAR_TOKEN
jdk:
  - openjdk8
service:
  - docker
jobs:
  include:
    - stage: unit test
      script:
        - gradle clean build -x test
    - stage: code scan
      script:
        - git clone --branch=devops https://github.com/singleton-demo/singleton-1.git devops
        - python $TRAVIS_BUILD_DIR/devops/sonar/config_sonar_project.py $SONAR_ORG:java-client:$TRAVIS_BRANCH $SONAR_ORG:java-client:$TRAVIS_BRANCH $SONAR_ORG java-client-gate $SONAR_TOKEN
        - gradle sonarqube --stacktrace -PsonarProjectKey=$SONAR_ORG:java-client:$TRAVIS_BRANCH -PsonarProjectName=$SONAR_ORG:java-client:$TRAVIS_BRANCH -Dsonar.branch.name=master
        - sleep 10 && cd $TRAVIS_BUILD_DIR/devops/sonar && python ./check_sonar_qualitygate.py -ProjectKeyPrefixArray=$SONAR_ORG:java-client:$TRAVIS_BRANCH
    - stage: smoke test
      script:
        - git clone --branch=master https://github.com/singleton-demo/singleton-1.git service
        - git clone --branch=devops https://github.com/singleton-demo/singleton-1.git devops
        - cd $TRAVIS_BUILD_DIR/service && ./gradlew build
        - cp $TRAVIS_BUILD_DIR/devops/deploy/i18n-service/Dockerfile $TRAVIS_BUILD_DIR/publish/
        - cd $TRAVIS_BUILD_DIR/service/publish && mv vip-manager-i18n-*.jar i18n-service.jar
        - docker build -t singleton .
        - docker run -d -p 8090:8090 --name singleton singleton
        - docker ps
        - cd $TRAVIS_BUILD_DIR && gradle clean build
        - cp $TRAVIS_BUILD_DIR/build/libs/vip4java-*.jar $TRAVIS_BUILD_DIR/devops/autotest/client/java/lib/
        - cd $TRAVIS_BUILD_DIR/devops/autotest/client/java && gradle build
        - docker cp l10n singleton:/
        - java -cp './target/*' org.testng.TestNG -d test-output ./target/testng.xml
  