dist: trusty

language: node_js

addons:
  sonarcloud:
    organization: $SONAR_ORG
    token:
      secure: $SONAR_TOKEN

node_js:
  - "10"
  
before_install:  
  - sudo apt-get -y install python3-pip python-dev
  - python3 -V
  - pip3 -V
install:
  - sudo pip3 install requests

jobs:
  include:
    - stage: unit test
      script:
        - npm install --registry https://registry.npmjs.org
        - npm run test
    - stage: code scan
      script:
        - npm install npm
        - npm install tslint
        - npm install typescript
        - tsc -v
        - git clone --branch=devops https://github.com/singleton-demo/singleton-1.git devops
        - cp devops/sonar/* .
        - rm -rf devops
        - python ./config_sonar_project.py $SONAR_ORG:singleton-js-core-sdk:$TRAVIS_BRANCH $SONAR_ORG:singleton-js-core-sdk:$TRAVIS_BRANCH $SONAR_ORG js-core-sdk-gate $SONAR_TOKEN
        - sonar-scanner -Dsonar.sources=. -Dsonar.projectName=$SONAR_ORG:singleton-js-core-sdk:$TRAVIS_BRANCH -Dsonar.branch.name=master -Dsonar.projectKey=$SONAR_ORG:singleton-js-core-sdk:$TRAVIS_BRANCH -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=$SONAR_ORG -Dsonar.login=$SONAR_TOKEN
        - sleep 5 && python3 ./check_sonar_qualitygate.py -ProjectKeyPrefixArray=$SONAR_ORG:singleton-js-core-sdk:$TRAVIS_BRANCH -HostName=https://sonarcloud.io
    - stage: auto test
      script:
        - mkdir -p g11n-js-client
        - shopt -s extglob
        - mv !(g11n-js-client) g11n-js-client/
        - mv .npmignore g11n-js-client/
        - git clone --branch=master https://github.com/singleton-demo/singleton-1.git service
        - git clone --branch=devops https://github.com/singleton-demo/singleton-1.git devops
        - mkdir -p service/g11n-ws/vip-manager-i18n/src/main/resources/l10n/bundles/
        - cp -a devops/test/bundles/JSCoreSDKTest service/g11n-ws/vip-manager-i18n/src/main/resources/l10n/bundles/
        - cd $TRAVIS_BUILD_DIR/service/g11n-ws && ./gradlew build -x test
        - cp $TRAVIS_BUILD_DIR/devops/deploy/i18n-service/Dockerfile $TRAVIS_BUILD_DIR/service/publish/
        - cd $TRAVIS_BUILD_DIR/service/publish && mv vip-manager-i18n-*.jar i18n-service.jar
        - docker build -t singleton .
        - docker run -d -p 8090:8090 -p 8091:8091 --name singleton singleton
        - docker ps
        - cd $TRAVIS_BUILD_DIR
        - cd g11n-js-client
        - sed -i 's:@vip/vip-core-sdk-server:@vip/vip-core-sdk-dev:' package.json
        - npm install --registry https://registry.npmjs.org
        - npm link
        - cd $TRAVIS_BUILD_DIR/devops/test/client/jscoresdk
        - npm install --registry https://registry.npmjs.org
        - npm link @vip/vip-core-sdk-dev
        - ./node_modules/.bin/jest
