dist: trusty
language: java
python:
  - "3.4"
addons:
  sonarcloud:
    organization: $SONAR_ORG
    token:
      secure: $SONAR_TOKEN
jdk:
  - openjdk8
service:
  - docker
before_install:
  - sudo apt-get -y install python3-pip python-dev
  - python3 -V
  - pip3 -V
install:
  - sudo pip3 install requests
jobs:
  include:
    - stage: unit test
      script:
        - cd $TRAVIS_BUILD_DIR/g11n-ws && ./gradlew build
    - stage: code scan
      script:
        - git clone --branch=devops https://github.com/vmware/singleton.git devops
        - python $TRAVIS_BUILD_DIR/devops/sonar/configsonar.py $SONAR_ORG:singleton-service:$TRAVIS_BRANCH $SONAR_ORG:singleton-service:$TRAVIS_BRANCH $SONAR_ORG service-gate $SONAR_TOKEN
        - cd $TRAVIS_BUILD_DIR/g11n-ws && sed -i "s/vip/$SONAR_ORG:singleton-service:$TRAVIS_BRANCH/" settings.gradle && cat settings.gradle
        - cd $TRAVIS_BUILD_DIR/g11n-ws && gradle sonarqube --stacktrace -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=$SONAR_ORG -Dsonar.branch.name=master --info
        - cd $TRAVIS_BUILD_DIR/devops/sonar && chmod 777 checkSonarQualityGateByAPI && ./checkSonarQualityGateByAPI -ProjectKeyPrefixArray=$SONAR_ORG:singleton-service:$TRAVIS_BRANCH
    - stage: auto test
      script:
        - git clone --branch=devops https://github.com/vmware/singleton.git devops
        - cd $TRAVIS_BUILD_DIR/g11n-ws && ./gradlew build
        - cp $TRAVIS_BUILD_DIR/devops/deploy/i18n-service/Dockerfile $TRAVIS_BUILD_DIR/publish/
        - cd $TRAVIS_BUILD_DIR/publish && mv vip-manager-i18n-*.jar i18n-service.jar
        - docker build -t singleton .
        - docker run -d -p 8090:8090 --name singleton singleton
        - docker ps
        - cd $TRAVIS_BUILD_DIR/devops/autotest/server/APITest && gradle build
        - docker cp l10n singleton:/
        - java -cp "target/*:resource/*" org.testng.TestNG testng.xml
