dist: trusty
language: node_js
addons:
  sonarcloud:
    organization: $SONAR_ORG
    token:
      secure: $SONAR_TOKEN
node_js:
  - "10"
python:
  - "3.4"
  
before_install:  
  - export CHROME_BIN=chromium-browser
  
jobs:
  include:
    - stage: unit test
      script:
        - sed -i "s/'Chrome'/'ChromeHeadless'/g" config/karma.conf.js
        - npm install --registry https://registry.npmjs.org
        - npm run test
    - stage: code scan
      script:
        - npm install npm
        - npm install tslint
        - npm install typescript
        - tsc -v
        - git clone --branch=devops https://github.com/singleton-demo/singleton-1.git devops
        - cp devops/sonar/js-clients/* .
        - rm -rf devops
        - python ./configsonar.py $SONAR_ORG:singleton:$TRAVIS_BRANCH $SONAR_ORG:singleton:$TRAVIS_BRANCH $SONAR_ORG jsclientgate $SONAR_TOKEN
        - sonar-scanner -Dsonar.sources=. -Dsonar.projectName=$SONAR_ORG:singleton' '$TRAVIS_BRANCH -Dsonar.projectKey=$SONAR_ORG:singleton:$TRAVIS_BRANCH -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=$SONAR_ORG -Dsonar.login=$SONAR_TOKEN
        - chmod 777 checkSonarQualityGateByAPI && ./checkSonarQualityGateByAPI -ProjectKeys=$SONAR_ORG:singleton -BranchName=$TRAVIS_BRANCH
